---
- name: AWS EC2 Instance Configuration
  hosts: localhost
  tasks: 
  - name: Validate plan
    ansible.builtin.uri:
      url: "{{ policy_as_code_plan_validation_url }}"
      method: POST
      body: '{ "input": { "tfplan": {{ tfshow.stdout }} } }'
      body_format: json
    check_mode: no
    register: validation_response
    failed_when:
      - validation_response.json.result.passes_validation == false
  - name: create instance
    amazon.aws.ec2_instance:
      name: "{{name}}"
      key_name: "{{ keypair }}"
      image_id: "{{ image }}"
      vpc_subnet_id: "{{vpc_subnet_id}}"
      instance_type: "{{instance_type}}"
      security_group: "{{security_group}}"
      wait: true
      count: 1
    register: ec2
  - name: add volume to instance
    amazon.aws.ec2_vol:
      instance: "{{ item.instance_id }}"
      volume_size: 40
    loop: "{{ ec2.instances }}"

  - name: Pause for 5 minutes to build app cache
    ansible.builtin.pause:
      seconds: 20

    #Get correct json input

  - name: get volume(s) info from EC2 Instance
    amazon.aws.ec2_vol_info:
      filters:
        attachment.instance-id: "{{ ec2.instances[0].instance_id }}"
    register: volumes

  - name: Save volume info to file
    copy:
      content: "{{ volumes | to_json | to_nice_json }}"
      dest: "input.json"
