---
- name: AWS EC2 Instance Configuration
  hosts: localhost
  tasks: 
  - name: Validate plan
    ansible.builtin.uri:
      url: "{{ policy_as_code_plan_validation_url }}"
      method: POST
      body: '{ "input": { "volume_size": {{volume_size}} } }'
      body_format: json
    register: validation_response
    failed_when:
      - validation_response.json.result.passes_validation == false
  - name: create instance
    amazon.aws.ec2_instance:
      name: "{{name}}"
      region: "us-east-2"
      key_name: "{{ keypair }}"
      image_id: "{{ image }}"
      vpc_subnet_id: "{{vpc_subnet_id}}"
      instance_type: "{{instance_type}}"
      security_group: "{{security_group}}"
      wait: true
      count: 1
    register: ec2
  - name: Pause for 5 minutes to build app cache
    ansible.builtin.pause:
      seconds: 60
  - name: add volume to instance
    amazon.aws.ec2_vol:
      instance: "{{ item.instance_id }}"
      volume_size: "{{volume_size}}"
    loop: "{{ ec2.instances }}"
